/**
 * fitness-records.service.js
 * Business logic for member fitness measurements.
 *
 * Responsibilities:
 *   - Create, update, list, and delete fitness records.
 *   - Let PostgreSQL generate BMI from weight/height.
 *   - Analyze progress between measurement snapshots.
 */

const repo = require('./fitness-records.repository');
const { buildBMISummary } = require('./bmiCalculator');
const { buildBodyFatSummary } = require('./bodyFatCalculator');
const { analyzeProgress } = require('./progressAnalyzer');
const { parse: parsePagination } = require('../../utils/Pagination');
const ApiError = require('../../utils/Apierror');
const logger = require('../../utils/Logger');

/**
 * Convert numeric strings from pg NUMERIC columns into JSON numbers.
 *
 * @param {unknown} value
 * @returns {number|null}
 */
const toNumberOrNull = (value) => {
  if (value === null || value === undefined || value === '') return null;
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
};

/**
 * Convert a record row into an API-friendly object with calculated labels.
 *
 * @param {object|null} record
 * @returns {object|null}
 */
const decorateRecord = (record) => {
  if (!record) return null;

  const weightKg = toNumberOrNull(record.weight_kg);
  const heightCm = toNumberOrNull(record.height_cm);
  const bodyFatPct = toNumberOrNull(
    record.body_fat_pct ?? record.body_fat_percent
  );
  const bmiSummary = buildBMISummary(weightKg, heightCm);
  const bmi = toNumberOrNull(record.bmi) ?? bmiSummary.bmi;

  return {
    ...record,
    weight_kg: weightKg,
    height_cm: heightCm,
    bmi,
    body_fat_pct: bodyFatPct,
    body_fat_percent: bodyFatPct,
    bmi_category: buildBMISummary(weightKg, heightCm).bmi_category,
    healthy_weight_range: bmiSummary.healthy_weight_range,
  };
};

/**
 * Remove API/calculator-only fields and map legacy aliases to DB columns.
 *
 * @param {object} data
 * @returns {object}
 */
const stripTransientFields = (data) => {
  const {
    sex: _sex,
    waist_cm: _waistCm,
    neck_cm: _neckCm,
    hip_cm: _hipCm,
    body_fat_percent: bodyFatPercent,
    recorded_at: recordedAt,
    ...persisted
  } = data;

  if (persisted.body_fat_pct === undefined && bodyFatPercent !== undefined) {
    persisted.body_fat_pct = bodyFatPercent;
  }

  if (persisted.recorded_date === undefined && recordedAt !== undefined) {
    persisted.recorded_date = recordedAt;
  }

  return persisted;
};

/**
 * Calculate derived body fat before insert.
 *
 * BMI is generated by the database, so the payload intentionally omits it.
 *
 * @param {object} data
 * @returns {object}
 */
const buildRecordPayload = (data) => {
  const bodyFatSummary = buildBodyFatSummary(data);
  const payload = stripTransientFields(data);

  return {
    ...payload,
    body_fat_pct: bodyFatSummary.body_fat_percent,
  };
};

/**
 * Merge existing record data with patch fields and prepare DB columns.
 *
 * @param {object} existing
 * @param {object} fields
 * @returns {object}
 */
const buildUpdatePayload = (existing, fields) => {
  const patch = stripTransientFields(fields);
  const hasExplicitBodyFat =
    fields.body_fat_pct !== undefined || fields.body_fat_percent !== undefined;
  const hasBodyFatMeasurementInput =
    fields.sex !== undefined ||
    fields.waist_cm !== undefined ||
    fields.neck_cm !== undefined ||
    fields.hip_cm !== undefined;

  if (hasExplicitBodyFat || hasBodyFatMeasurementInput) {
    const bodyFatSummary = buildBodyFatSummary({
      ...existing,
      ...fields,
    });
    patch.body_fat_pct = bodyFatSummary.body_fat_percent;
  }

  return patch;
};

/**
 * Create a new fitness record for a member.
 *
 * @param {string} userId
 * @param {object} data
 * @returns {Promise<object>}
 */
const createRecord = async (userId, data) => {
  const payload = buildRecordPayload({
    ...data,
    user_id: userId,
  });

  const record = await repo.createRecord(payload);
  logger.info('Fitness record created', { userId, recordId: record.id });
  return decorateRecord(record);
};

/**
 * List the authenticated member's records.
 *
 * @param {string} userId
 * @param {object} query
 * @returns {Promise<{ records: object[], total: number, page: number, limit: number }>}
 */
const listMyRecords = async (userId, query = {}) => {
  const { page, limit, offset } = parsePagination(query);
  const { rows, total } = await repo.findAll({
    user_id: userId,
    from_date: query.from_date,
    to_date: query.to_date,
    limit,
    offset,
  });

  return {
    records: rows.map(decorateRecord),
    total,
    page,
    limit,
  };
};

/**
 * Admin: list records across all users.
 *
 * @param {object} query
 * @returns {Promise<{ records: object[], total: number, page: number, limit: number }>}
 */
const listAllRecords = async (query = {}) => {
  const { page, limit, offset } = parsePagination(query);
  const { rows, total } = await repo.findAll({
    user_id: query.user_id,
    from_date: query.from_date,
    to_date: query.to_date,
    limit,
    offset,
  });

  return {
    records: rows.map(decorateRecord),
    total,
    page,
    limit,
  };
};

/**
 * Get one record owned by the authenticated member.
 *
 * @param {string} recordId
 * @param {string} userId
 * @returns {Promise<object>}
 */
const getMyRecordById = async (recordId, userId) => {
  const record = await repo.findByIdAndUser(recordId, userId);
  if (!record) throw ApiError.notFound('Fitness record');
  return decorateRecord(record);
};

/**
 * Admin: get any record by ID.
 *
 * @param {string} recordId
 * @returns {Promise<object>}
 */
const getRecordById = async (recordId) => {
  const record = await repo.findById(recordId);
  if (!record) throw ApiError.notFound('Fitness record');
  return decorateRecord(record);
};

/**
 * Get the authenticated member's latest record.
 *
 * @param {string} userId
 * @returns {Promise<object>}
 */
const getLatestRecord = async (userId) => {
  const record = await repo.findLatestByUser(userId);
  if (!record) throw ApiError.notFound('Fitness record');
  return decorateRecord(record);
};

/**
 * Update a record owned by the authenticated member.
 *
 * @param {string} recordId
 * @param {string} userId
 * @param {object} fields
 * @returns {Promise<object>}
 */
const updateRecord = async (recordId, userId, fields) => {
  const existing = await repo.findByIdAndUser(recordId, userId);
  if (!existing) throw ApiError.notFound('Fitness record');

  const payload = buildUpdatePayload(existing, fields);
  const updated = await repo.updateRecord(recordId, userId, payload);

  logger.info('Fitness record updated', { userId, recordId });
  return decorateRecord(updated);
};

/**
 * Delete a record owned by the authenticated member.
 *
 * @param {string} recordId
 * @param {string} userId
 * @returns {Promise<void>}
 */
const deleteRecord = async (recordId, userId) => {
  const existing = await repo.findByIdAndUser(recordId, userId);
  if (!existing) throw ApiError.notFound('Fitness record');

  await repo.deleteRecord(recordId, userId);
  logger.info('Fitness record deleted', { userId, recordId });
};

/**
 * Analyze a member's progress.
 *
 * @param {string} userId
 * @param {object} query
 * @returns {Promise<object>}
 */
const getProgress = async (userId, query = {}) => {
  const records = await repo.findForProgress({
    user_id: userId,
    from_date: query.from_date,
    to_date: query.to_date,
    limit: query.limit,
  });

  const decorated = records.map(decorateRecord);
  return analyzeProgress(decorated, { goal: query.goal });
};

module.exports = {
  createRecord,
  listMyRecords,
  listAllRecords,
  getMyRecordById,
  getRecordById,
  getLatestRecord,
  updateRecord,
  deleteRecord,
  getProgress,

  // Exported for focused unit tests.
  buildRecordPayload,
  decorateRecord,
};
